# fly.toml app configuration file generated for sdfsdfsdfs-1726634969-client on 2024-09-18T04:50:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sdfsdfsdfs-1726634969-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
